[project]
name = "events-aggregator"
version = "0.1.0"
description = "Сервис-агрегатор для Events Provider API"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.0",
    "uvicorn[standard]>=0.30.6",
    "sqlalchemy[asyncio]>=2.0.35",
    "asyncpg>=0.29.0",
    "alembic>=1.13.2",
    "pydantic[email]>=2.9.2",
    "pydantic-settings>=2.5.2",
    "httpx>=0.27.2",
]

[dependency-groups]
dev = [
    "pytest>=8.3.2",
    "pytest-asyncio>=0.24.0",
    "ruff>=0.6.9",
]

[tool.ruff]
line-length = 100
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I", "N", "W", "D", "UP", "B", "C4", "SIM"]
ignore = ["D203", "D213"]

# Все исключения — в ОДНОЙ секции
[tool.ruff.lint.per-file-ignores]
"tests/*" = ["D103", "D101", "D102"]
"__init__.py" = ["D104"]
"alembic/versions/*" = ["D400", "D415", "D103", "UP035", "UP007", "I001"]
"src/client/events_provider.py" = ["D105", "D107"]
"src/client/paginator.py" = ["D105", "D107"]
"src/repositories/base.py" = ["D107", "UP046"]
"src/services/*.py" = ["D102", "D107"]
"src/api/deps.py" = ["D103"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]
